version: '1'
services:
  im-cake-manager:
    image: im-cake-manager-1.0-SNAPSHOT
    ports: 
      - "8080:8080"
    depends_on: 
      - db

  db:
    image: mysql
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
    ports: 
- "3306:3306"
