spring:
  application:
    name: im-cake-manager
  h2:
    console:
      enabled: true
      path: /console/
  datasource:
    url: jdbc:h2:mem:cakedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=ORACLE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2